import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export default {
    default: [
        {
            type: 'doc',
            id: 'index',
            label: 'Привет!'
        },
        {
            type: 'doc',
            id: 'important',
            label: 'Обязательно к прочтению'
        },
        {
            type: 'category',
            label: 'Иммунология',
            items: [
                {
                    type: 'category',
                    label: 'Сахарный диабет I типа',
                    link: {
                        type: 'doc',
                        id: 'immunology/diabetes'
                    },
                    items: [
                        {
                            type: 'ref',
                            id: 'for-curious/insulin-for-a-healthy-person',
                            label: 'Что будет, если здоровый человек примет инсулин?'
                        }
                    ]
                },
                {
                    type: 'autogenerated',
                    dirName: 'immunology'
                }
            ]
        },
        {
            type: 'category',
            label: 'Для любопытных',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'for-curious'
                }
            ]
        }
    ]
} as SidebarsConfig;